specVersion: "0.2.0"

name: "Blockplace"
version: "1.0.0"
description: "Blockplace Transactions"
repository: "https://github.com/kenjicncr/movrplace-subquery"

schema:
  file: "./schema.graphql"

network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Genesis hash of Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws

  chaintypes:
    file: "./types.yaml"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1661141
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: contract
        address: '0xFEf7D59B26F60A253e0cd34850aCa419f16Ebb2E'
    assets:
      contract:
        file: './movrplace.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleStorePixels
          kind: substrate/MoonbeamCall
          filter:
            function: storePixels((uint256,uint256,uint16)[], string, string)
